/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apresentacao;

import javax.swing.JOptionPane;

/**
 *
 * @author tiago
 */
public class TelaJogo extends javax.swing.JFrame {

    private TelaJogadores veioDoTelaJogadores;
    
    /**
     * Creates new form TelaJogo
     */
    public TelaJogo() {
        initComponents();

    }

    public void enviaPalavra(TelaJogadores veioDo1, String nome, TelaJogadores veioDo2, String nome2){
        jTFJogador1.setText(nome);
        jTFJogador2.setText(nome2);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTFJogador1 = new javax.swing.JTextField();
        jCBJogador1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFJogador2 = new javax.swing.JTextField();
        jCBJogador2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Escolha a Jogada"));

        jLabel6.setText("Jogador 1:");

        jLabel7.setText("Jogada:");

        jTFJogador1.setEditable(false);

        jCBJogador1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha a jogada", "Pedra", "Papel", "Tesoura" }));

        jLabel1.setText("Jogador 2:");

        jLabel2.setText("Jogada:");

        jTFJogador2.setEditable(false);

        jCBJogador2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha a jogada", "Pedra", "Papel", "Tesoura" }));

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Jogar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addGap(106, 106, 106))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFJogador1)
                    .addComponent(jCBJogador1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTFJogador2)
                    .addComponent(jCBJogador2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTFJogador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jCBJogador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFJogador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCBJogador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // inicio dos teste de validação

        if (jCBJogador1.getSelectedIndex() == 0) {  // VERIFICA SE O CAMPO DA JOGADA  DO JOGADOR 1 ESTA VAZIO
            System.out.println("Preencha a jogada do Jogador 1 !");
            JOptionPane.showMessageDialog(null, "Preencha a jogada do Jogador 1 !");
        } else {
            if (jCBJogador2.getSelectedIndex() == 0) {  // VERIFICA SE O CAMPO DA JOGADA DO JOGADOR 2 ESTA VAZIO
                System.out.println("Preencha a jogada do Jogador 2 !");
                JOptionPane.showMessageDialog(null, "Preencha a jogada do Jogador 2 !");
            } else {
                if ((jCBJogador1.getSelectedIndex() == 1) && (jCBJogador2.getSelectedIndex() == 1)) {   // QUANDO A JOGADA DÁ EMPATE
                    System.out.println("Empate!");
                    JOptionPane.showMessageDialog(null, "Empate!");
                } else {
                    if ((jCBJogador1.getSelectedIndex() == 2) && (jCBJogador2.getSelectedIndex() == 2)) {   // QUANDO A JOGADA DÁ EMPATE
                        System.out.println("Empate!");
                        JOptionPane.showMessageDialog(null, "Empate!");
                    } else {
                        if ((jCBJogador1.getSelectedIndex() == 3) && (jCBJogador2.getSelectedIndex() == 3)) {   // QUANDO A JOGADA DÁ EMPATE
                            System.out.println("Empate!");
                            JOptionPane.showMessageDialog(null, "Empate!");
                        } else {
                            if ((jCBJogador1.getSelectedIndex() == 1) && (jCBJogador2.getSelectedIndex() == 2)) {   // QUANDO O JOGADOR 2 GANHA A JOGADA (PEDRA-PAPEL)
                                System.out.println("Jogador 2 Venceu!");
                                JOptionPane.showMessageDialog(null, "Jogador 2 Venceu!");
                            } else {
                                if ((jCBJogador1.getSelectedIndex() == 1) && (jCBJogador2.getSelectedIndex() == 3)) {   // QUANDO O JOGADOR 1 GANHA A JOGADA (PEDRA-TESOURA)
                                    System.out.println("Jogador 1 Venceu!");
                                    JOptionPane.showMessageDialog(null, "Jogador 1 Venceu!");
                                } else {
                                    if ((jCBJogador1.getSelectedIndex() == 2) && (jCBJogador2.getSelectedIndex() == 1)) {   // QUANDO O JOGADOR 1 GANHA A JOGADA (PAPEL-PEDRA)
                                        System.out.println("Jogador 1 Venceu!");
                                        JOptionPane.showMessageDialog(null, "Jogador 1 Venceu!");
                                    } else {
                                        if ((jCBJogador1.getSelectedIndex() == 2) && (jCBJogador2.getSelectedIndex() == 3)) {   // QUANDO O JOGADOR 2 GANHA A JOGADA (PAPEL-TESOURA)
                                            System.out.println("Jogador 2 Venceu!");
                                            JOptionPane.showMessageDialog(null, "Jogador 2 Venceu!");
                                        } else {
                                            if ((jCBJogador1.getSelectedIndex() == 3) && (jCBJogador2.getSelectedIndex() == 1)) {   // QUANDO O JOGADOR 2 GANHA A JOGADA (TESOURA-PEDRA)
                                                System.out.println("Jogador 2 Venceu!");
                                                JOptionPane.showMessageDialog(null, "Jogador 2 Venceu!");
                                            } else {
                                                if ((jCBJogador1.getSelectedIndex() == 3) && (jCBJogador2.getSelectedIndex() == 2)) {   // QUANDO O JOGADOR 1 GANHA A JOGADA (TESOURA-PAPEL)
                                                    System.out.println("Jogador 1 Venceu!");
                                                    JOptionPane.showMessageDialog(null, "Jogador 1 Venceu!");
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        jCBJogador1.setSelectedIndex(0);
        jCBJogador2.setSelectedIndex(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaJogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jCBJogador1;
    private javax.swing.JComboBox<String> jCBJogador2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTFJogador1;
    private javax.swing.JTextField jTFJogador2;
    // End of variables declaration//GEN-END:variables
}
